version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3030:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
